GET http://localhost:8080/notices
Accept: application/json

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "mobileNumber": "45678901234",
  "pwd": "12345",
  "role": "user"
}

###
GET http://localhost:8080/welcome
Accept: application/json

###


