POST http://localhost:8080/register
Content-Type: application/json

{
  "email": "john@example.com",
  "pwd": "12345",
  "role": "user"
}

###
GET http://localhost:8080/welcome
Accept: application/json

###

